project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        text: Internship Overview
      - visualisations.qmd
        text: My Visualisations
      - reflection.qmd
        text: Reflection on Use of GenAI

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



